select * from SIIE.v_alumnos_inscritos;
select * from SIIE.v_boletas_evaluacion;

SELECT
SubStr(CURP,0,16) AS RAIZ_CURP, -- CARACTER	16	RAÍZ DE LA CURP DEL ALUMNO	OOST070821MDFRNN
CURP, --	CARACTER	18	CURP COMPLETA DEL ALUMNO	OOST070821MDFRNNA5
to_char(TO_DATE(fecha_nacimiento,'DD/MM/YY'),'MM/DD/YY') AS FECH_NAC, --	CARACTER	8	FECHA DE NACIMIENTO DEL ALUMNO (MM/DD/AA)	08/21/07
PRIMER_APELLIDO AS PATERNO, --	CARACTER	35	APELLIDO PATERNO DEL ALUMNO	OROZCO
SEGUNDO_APELLIDO AS MATERNO, --	CARACTER	35	APELLIDO MATERNO DEL ALUMNO	SANCHEZ
NOMBRES AS NOMBRE, --	CARACTER	40	NOMBRE (S)  DEL ALUMNO	TANIA BERENICE
GENERO AS SEXO, --	CARACTER	1	SEXO DEL ALUMNO (UTILIZAR ÚNICAMENTE CLAVES PRESTABLECIDAS)
--          H = HOMBRE
--          M = MUJER	M
ENTIDAD_NACIMIENTO_ABREVIACION AS ENT_NAC, --	CARACTER	2	CLAVE DE LA ENTIDAD DE NACIMIENTO DEL  ALUMNO	DF
CASE when SUBSTR(TURNO,1,1) in ('M','V','N','J') THEN SUBSTR(TURNO,1,1)
     ELSE 'C' END AS TURNO, --	CARACTER	1	TURNO EN EL QUE ESTUDIA EL ALUMNO (UTILIZAR ÚNICAMENTE CLAVES PRESTABLECIDAS)
--            M = MATUTINO
--            V = VESPERTINO
--            N = NOCTURNO
--            D = DISCONTINUO	M
CCT, --	CARACTER	10	CLAVE DEL CENTRO DE TRABAJO DONDE ESTUDIA EL ALUMNO	09PES0112Q
TUTOR_CALLE || TUTOR_NUMERO_EXTERIOR || TUTOR_NUMERO_INTERIOR AS CALLE, --	CARACTER	80	CALLE Y NÚMERO DEL DOMICILIO PARTICULAR DEL ALUMNO	NECAXA 154
TUTOR_COLONIA AS COLONIA, --	CARACTER	60	COLONIA DEL DOMICILIO PARTICULAR DEL ALUMNO	PORTALES
TUTOR_ENTIDAD_ID AS EDO, --	CARACTER	2	CLAVE DE LA ENTIDAD DEL DOMICILIO PARTICULAR DEL ALUMNO	09
TUTOR_ALCALDIA_MUNICIPIO_ID AS DELMUN, --	CARACTER	3	CLAVE DE LA ALCALDÍA DEL DOMICILIO PARTICULAR DEL ALUMNO	003
TUTOR_ALCALDIA_MUNICIPIO AS N_DELMUN, --	CARACTER	60	NOMBRE DE LA ALCALDÍA DEL DOMICILIO PARTICULAR DEL ALUMNO	BENITO JUÁREZ
TUTOR_CODIGO_POSTAL AS CODPOS, --	CARACTER	5	CÓDIGO POSTAL DEL DOMICILIO PARTICULAR DEL ALUMNO	03660
TUTOR_CELULAR_O_TELEFONO_FIJO AS TELEFONO, --	CARACTER	13	TELÉFONO DEL DOMICILIO PARTICULAR DEL ALUMNO (SIN GUIONES)	85006364
STATUS AS STATUS,  --	CARACTER	1	SITUACIÓN ACADÉMICA ACTUAL DEL ALUMNO (UTILIZAR ÚNICAMENTE CLAVES PRESTABLECIDAS)
--              R = REGULAR
--              I = IRREGULAR	R
ADEUDO AS ADEUDO, --	NÚMERICO	1	NÚMERO DE ASIGNATURAS QUE ADEUDA EL ALUMNO	0
NULL AS OBSERVA --	CARACTER	60	OBSERVACIONES	NINGUNA
FROM SIIE.V_ALUMNOS_INSCRITOS where grado = 3;