CREATE TABLE PROCESA_INFORMACION.VALIDA_ALUMNOS_FIDEGAR
(
  ID                    NUMBER(19)              NOT NULL,
  ALUMNO_CURP           VARCHAR2(18 BYTE)       NOT NULL,
  ALUMNO_NOMBRE         VARCHAR2(60 BYTE)       NOT NULL,
  ALUMNO_PRIMER_AP      VARCHAR2(60 BYTE)       NOT NULL,
  ALUMNO_SEGUNDO_AP     VARCHAR2(60 BYTE),
  CCT                   VARCHAR2(10 BYTE)       NOT NULL,
  NIVEL                 VARCHAR2(10 BYTE)       NOT NULL,
  GRADO                 VARCHAR2(20 BYTE),      NOT NULL,
  ALCALDIA              VARCHAR2(128 BYTE)      NOT NULL,
  CCT_AEFCM             VARCHAR2(10 BYTE),
  NIVEL_AEFCM           VARCHAR2(15 BYTE),
  GRADO_AEFCM           VARCHAR2(20 BYTE),
  USUARIO_CREACION      VARCHAR2(32 BYTE)       NOT NULL,
  FECHA_CREACION        DATE                    NOT NULL,
  USUARIO_MODIFICACION  VARCHAR2(32 BYTE),
  FECHA_ACTUALIZACION   DATE
)
;

CREATE INDEX PROCESA_INFORMACION.IDX_VALIDA_ALU_FIDEGAR_CCT ON PROCESA_INFORMACION.VALIDA_ALUMNOS_FIDEGAR
(CCT)
;

CREATE UNIQUE INDEX PROCESA_INFORMACION.IDX_VALIDA_ALU_FIDEGAR_CURP ON PROCESA_INFORMACION.VALIDA_ALUMNOS_FIDEGAR
(ALUMNO_CURP)
;
